on: [ push, pull_request ]
name: Continuous Integration

jobs:
  inspect-code:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET 3.1.x LTS
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"

      - name: Install .NET 6.0.x LTS
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Restore .NET Tools
        run: dotnet tool restore

      - name: Restore .NET Packages
        run: dotnet restore yambar-templates.sln

      # - name: Restore InspectCode Cache
      #   uses: actions/cache@v3
      #   with:
      #     path: ${{ github.workspace }}/inspectcode
      #     key: inspectcode-${{ hashFiles('.config/dotnet-tools.json', '.github/workflows/ci.yml', 'yambar-templates.sln*', '.editorconfig') }}

      # - name: .NET Code Style
      #   run: dotnet build -c Debug -warnaserror yambar.Templates.csproj -p:EnforceCodeStyleInBuild=true

      # - name: Inspect Code
      #   run: dotnet jb inspectcode $(pwd)/yambar-templates.slnf --no-build --output="inspectcodereport.xml" --caches-home="inspectcode" --verbosity=WARN

      # - name: NVika
      #   run: dotnet nvika parsereport "${{github.workspace}}/inspectcodereport.xml" --treatwarningsaserrors
